language: node_js

node_js:
  - '9'

cache: yarn

script:
  - yarn install
  - yarn run test
deploy:
  provider: heroku
  api_key:
    secure: cgLRRrpTBmh7SbopBG5X3dPLfmOT58LQemj3bhGkXlLFYorSnhL7X8BlIsVRxLT0zSl84cX8rhD8mXrUoDYGoiNTFExMVcoUDxBfzNBqmAR8XGej0OUaEdwqyK8kFgDmLeXhOCd8ZQMDMTgR0fyzD6/kPYNf4BC6LHPF4sFVdvfLA0XWEpAkwQ2GdjZ82XN7U4rPua5H4hXJm+8kYlNo3lHHlXSAjcxL52g+otTlzCD26tuH8/G7QCux0R2xhBicqNBlgTpote6MbX2wer4srtqbvDLFxjbdbMSah23wAfxjK97sbfBHhfo+M14hGWBZ4Vqrf15RRqoKWjw+j4pycGkgn+ZRNS4inejKoEpKd1Vsab4WoIJAtAuF/FpuhsqZ1NRHKgJd3bI6x9SpKjtZnU5Pz/aSwZbLidnf9kl3bH5ylB8c4zMKrmNJsnyGrvz7lGemzBK+bNph4py2t0ziAq3s6QFTxG+NOqbyxzReVzwpeJ4PeKaTq7qiYxzv+ieY9zOvpwfVIuLxC7PkNVa/rCsMXoisDYUTO7dntibiExIXJODZGqI6e/kZzLWI6WTOwL1D8i1gaywZ/LbpJK2rQ3E48NO2vc8CoN1mCBanwpVGaNqPtoYe3sDie7Y+1MH5XA27eKb0MiTGcOxcGGkf1gm7iTrbe5YnEMkS/0KcC14=
